### ISSUE TITLE
Wanted to confirm if the generated yaml file is correct

### ISSUE THREAD

**Issue by sparshgarg23** [eric612/BDD100k-toolkit#7]
Hi,
I ran your code on my own to generate the BDD100K yaml file,was able to generate it succesfully,just wanted to check if this is the same file you get on your end.
I have changed the paths for my use as well I have commented out the shutil.move parts.
Also,I noticed that the number of segmentation classes comes out to be 2 ,is that correct?
BDD100K yaml file
```
classes:
  map: [person, rider, car, bus, truck, bike, motor]
  original: [person, rider, car, bus, truck, bike, motor, traffic light, traffic sign,
    train]
extention_names:
  annotation: [json]
  image: [jpg]
  segmentation: [png]
model_config_path: models/bdd100k/config.yaml
segmentation_anno_keywords: id
segmentation_enable: true
segmentation_num_classes: 2
test_dataset_path:
  annos: [/content/data/bdd100k/annotations/val]
  imgs: [/content/BDD100k-toolkit/images/val]
  lists: [/content/data/ImageSets/val.txt]
  lmdb: bdd100k-test-lmdb
  name: bdd100k_test
  segs: [/content/data/drivable_maps/labels/val/]
trainval_dataset_path:
  annos: [/content/data/bdd100k/annotations/train]
  imgs: [/content/data/images/train]
  lists: [/content/data/ImageSets/train.txt]
  lmdb: bdd100k-train-lmdb
  name: bdd100k_train
  segs: [/content/data/drivable_maps/labels/train/]

```
Also,now that the yaml file has been generated,we can directly use this for training right.
